[tools]
python = "3.11"

[env]
_.python.venv = { path = ".venv", create = true }
_.path = [
    "/opt/homebrew/opt/avr-gcc@8/bin",
    "/opt/homebrew/opt/arm-none-eabi-gcc@8/bin",
    "/opt/homebrew/opt/arm-none-eabi-binutils/bin",
]
